# -*- coding: shift_jis -*-
print("Hello World!")
print("git init で初期化")
print("git add でステージングエリアに追加")
print("git rm でステージングエリアから削除")
print("git commit でローカルリポジトリにコミット")
print("git log でコミットの履歴を確認")
print("git status で最新のコミットから現在までの差分を確認")
print("git diff でステージ・コミット・ローカルの変更差分を確認")
print("git push origin master でmasterブランチへ変更をプッシュ")
